// <auto-generated />
namespace MetaHealth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_sepmood_reason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sepmood_reason));
        
        string IMigrationMetadata.Id
        {
            get { return "202003312104226_add_sepmood_reason"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
