DROP TABLE [dbo].[SepMoods]
DROP TABLE [dbo].[CustomList]
DROP TABLE [dbo].[AspNetUserRoles]
DROP TABLE [dbo].[AspNetUserClaims]
DROP TABLE [dbo].[AspNetUserLogins]
DROP TABLE [dbo].[AspNetRoles]
DROP TABLE [dbo].[AspNetUsers]